// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDakshl3ycAt3DYERM2zF4e8OEkzsKfOB4',
    appId: '1:422201180001:web:16e0d420fa2ec0b26dcf20',
    messagingSenderId: '422201180001',
    projectId: 'fir-notification-48bb0',
    authDomain: 'fir-notification-48bb0.firebaseapp.com',
    storageBucket: 'fir-notification-48bb0.firebasestorage.app',
    measurementId: 'G-9NQJW66NBX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClZmKoaGhZI_6ThIggfPJ-a14ysT3A7y0',
    appId: '1:422201180001:android:d1927c4711fbdcd46dcf20',
    messagingSenderId: '422201180001',
    projectId: 'fir-notification-48bb0',
    storageBucket: 'fir-notification-48bb0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdp3VKddSKTiQkmeeLsRxbSL9tXIVuIFM',
    appId: '1:422201180001:ios:9c2841cb23028f026dcf20',
    messagingSenderId: '422201180001',
    projectId: 'fir-notification-48bb0',
    storageBucket: 'fir-notification-48bb0.firebasestorage.app',
    iosBundleId: 'com.example.pushNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdp3VKddSKTiQkmeeLsRxbSL9tXIVuIFM',
    appId: '1:422201180001:ios:9c2841cb23028f026dcf20',
    messagingSenderId: '422201180001',
    projectId: 'fir-notification-48bb0',
    storageBucket: 'fir-notification-48bb0.firebasestorage.app',
    iosBundleId: 'com.example.pushNotification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDakshl3ycAt3DYERM2zF4e8OEkzsKfOB4',
    appId: '1:422201180001:web:d53c784865fa41366dcf20',
    messagingSenderId: '422201180001',
    projectId: 'fir-notification-48bb0',
    authDomain: 'fir-notification-48bb0.firebaseapp.com',
    storageBucket: 'fir-notification-48bb0.firebasestorage.app',
    measurementId: 'G-E8Y9VY0Y60',
  );
}
